# .goreleaser.yml
project_name: SMBScanner

before:
  hooks:
    - go mod download golang.org/x/crypto
    - go mod download golang.org/x/net 
    - go mod download github.com/stacktitan/smb
    - go mod tidy
    

builds:
  # GOOS list to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are darwin and linux.
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows  # You can have multiple builds defined as a yaml list
  # GOARCH to build for.
  # For more info refer to: https://golang.org/doc/install/source#environment
  # Defaults are 386 and amd64.
#  goarch:
#    - amd64
#    - 386
   
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: MacOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
      
checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_checksums.txt"
  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  algorithm: sha256